version: 1
merge:
  whitelist:
    labels: ["autopep8"]
  blacklist:
    labels: ["do not merge"]
  method: squash
  options:
    squash:
      body: pull_request_body
      message_delimiter: ==COMMIT_MSG==
  delete_after_merge: false
update:
  whitelist:
    labels: ["autopep8"]
