name: Format python code
on: push
jobs:
  autopep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: autopep8
        uses: peter-evans/autopep8@v1
        with:
          args: --recursive --in-place --aggressive --aggressive .
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          commit-message: autopep8 Fixes
          committer: Bruno Alexander Cremonese de Morais <brualexander@gmail.com>
          title: Fixes by autopep8
          body: Fixes by autopep8
          labels: autopep8
          reviewers: brucremo
          branch: autopep8-patches
